<?php

namespace SmartTill\Core\Support;

class CorePermissionCatalog
{
    public static function definitions(): array
    {
        return [
            'store' => [
                'Sales' => [
                    ['name' => 'View Sales', 'description' => 'View sales transactions and history'],
                    ['name' => 'Create Sales', 'description' => 'Create new sales transactions'],
                    ['name' => 'Edit Sales', 'description' => 'Edit existing sales transactions'],
                    ['name' => 'Delete Sales', 'description' => 'Delete sales transactions'],
                    ['name' => 'Print Sales', 'description' => 'Print sale receipts and invoices'],
                    ['name' => 'Export Sales', 'description' => 'Export sales data to CSV/Excel'],
                    ['name' => 'Manage FBR Invoices', 'description' => 'Generate and regenerate FBR invoices and refund invoices'],
                    ['name' => 'Mark Sales as Paid', 'description' => 'Mark sales transactions as paid'],
                    ['name' => 'Mark Sales as Cancelled', 'description' => 'Cancel sales transactions'],
                ],
                'Products' => [
                    ['name' => 'View Products', 'description' => 'View products and their details'],
                    ['name' => 'Create Products', 'description' => 'Create new products'],
                    ['name' => 'Edit Products', 'description' => 'Edit existing products'],
                    ['name' => 'Delete Products', 'description' => 'Delete products'],
                    ['name' => 'Import Products', 'description' => 'Import products from CSV file'],
                    ['name' => 'Force Delete Products', 'description' => 'Permanently delete products'],
                    ['name' => 'Restore Products', 'description' => 'Restore deleted products'],
                ],
                'Variations' => [
                    ['name' => 'View Variations', 'description' => 'View product variations'],
                    ['name' => 'Edit Variations', 'description' => 'Edit product variations'],
                    ['name' => 'Import Variation Stock', 'description' => 'Import stock levels for variations'],
                    ['name' => 'Export Variations', 'description' => 'Export variations data'],
                    ['name' => 'Manage Stock', 'description' => 'Add and edit stock entries for variations'],
                    ['name' => 'View Variation Transactions', 'description' => 'View variation transaction history'],
                ],
                'Categories' => [
                    ['name' => 'View Categories', 'description' => 'View product categories'],
                    ['name' => 'Create Categories', 'description' => 'Create new categories'],
                    ['name' => 'Edit Categories', 'description' => 'Edit existing categories'],
                    ['name' => 'Delete Categories', 'description' => 'Delete categories'],
                    ['name' => 'Import Categories', 'description' => 'Import categories from CSV'],
                    ['name' => 'Export Categories', 'description' => 'Export categories data'],
                    ['name' => 'Force Delete Categories', 'description' => 'Permanently delete categories'],
                    ['name' => 'Restore Categories', 'description' => 'Restore deleted categories'],
                ],
                'Brands' => [
                    ['name' => 'View Brands', 'description' => 'View product brands'],
                    ['name' => 'Create Brands', 'description' => 'Create new brands'],
                    ['name' => 'Edit Brands', 'description' => 'Edit existing brands'],
                    ['name' => 'Delete Brands', 'description' => 'Delete brands'],
                    ['name' => 'Import Brands', 'description' => 'Import brands from CSV'],
                    ['name' => 'Export Brands', 'description' => 'Export brands data'],
                    ['name' => 'Force Delete Brands', 'description' => 'Permanently delete brands'],
                    ['name' => 'Restore Brands', 'description' => 'Restore deleted brands'],
                ],
                'Attributes' => [
                    ['name' => 'View Attributes', 'description' => 'View product attributes'],
                    ['name' => 'Create Attributes', 'description' => 'Create new attributes'],
                    ['name' => 'Edit Attributes', 'description' => 'Edit existing attributes'],
                    ['name' => 'Delete Attributes', 'description' => 'Delete attributes'],
                    ['name' => 'Force Delete Attributes', 'description' => 'Permanently delete attributes'],
                    ['name' => 'Restore Attributes', 'description' => 'Restore deleted attributes'],
                ],
                'Units' => [
                    ['name' => 'View Units', 'description' => 'View measurement units'],
                    ['name' => 'Create Units', 'description' => 'Create new units'],
                    ['name' => 'Edit Units', 'description' => 'Edit existing units'],
                    ['name' => 'Delete Units', 'description' => 'Delete units'],
                    ['name' => 'Import Units', 'description' => 'Import units from CSV'],
                    ['name' => 'Export Units', 'description' => 'Export units data'],
                    ['name' => 'Force Delete Units', 'description' => 'Permanently delete units'],
                    ['name' => 'Restore Units', 'description' => 'Restore deleted units'],
                ],
                'Customers' => [
                    ['name' => 'View Customers', 'description' => 'View customer information'],
                    ['name' => 'Create Customers', 'description' => 'Create new customers'],
                    ['name' => 'Edit Customers', 'description' => 'Edit customer information'],
                    ['name' => 'Delete Customers', 'description' => 'Delete customers'],
                    ['name' => 'Force Delete Customers', 'description' => 'Permanently delete customers'],
                    ['name' => 'Restore Customers', 'description' => 'Restore deleted customers'],
                    ['name' => 'Receive Payment from Customers', 'description' => 'Receive payments from customers and add receivables'],
                    ['name' => 'View Customer Transactions', 'description' => 'View customer transaction history'],
                ],
                'Suppliers' => [
                    ['name' => 'View Suppliers', 'description' => 'View supplier information'],
                    ['name' => 'Create Suppliers', 'description' => 'Create new suppliers'],
                    ['name' => 'Edit Suppliers', 'description' => 'Edit supplier information'],
                    ['name' => 'Delete Suppliers', 'description' => 'Delete suppliers'],
                    ['name' => 'Force Delete Suppliers', 'description' => 'Permanently delete suppliers'],
                    ['name' => 'Restore Suppliers', 'description' => 'Restore deleted suppliers'],
                    ['name' => 'Pay to Suppliers', 'description' => 'Record payments made to suppliers'],
                    ['name' => 'View Supplier Transactions', 'description' => 'View supplier transaction history'],
                ],
                'Purchase Orders' => [
                    ['name' => 'View Purchase Orders', 'description' => 'View purchase orders'],
                    ['name' => 'Create Purchase Orders', 'description' => 'Create new purchase orders'],
                    ['name' => 'Edit Purchase Orders', 'description' => 'Edit purchase orders'],
                    ['name' => 'Delete Purchase Orders', 'description' => 'Delete purchase orders'],
                    ['name' => 'Close Purchase Orders', 'description' => 'Close/receive purchase orders'],
                    ['name' => 'Print Purchase Orders', 'description' => 'Print purchase order documents'],
                    ['name' => 'Cancel Purchase Orders', 'description' => 'Cancel closed purchase orders'],
                    ['name' => 'Force Delete Purchase Orders', 'description' => 'Permanently delete purchase orders'],
                    ['name' => 'Restore Purchase Orders', 'description' => 'Restore deleted purchase orders'],
                ],
                'Cash Transactions' => [
                    ['name' => 'View Cash Transactions', 'description' => 'View cash transactions history'],
                ],
                'Payments' => [
                    ['name' => 'View Payments', 'description' => 'View payments history'],
                    ['name' => 'Print Payments', 'description' => 'Print payment receipts'],
                ],
                'Users' => [
                    ['name' => 'View Users', 'description' => 'View store users'],
                    ['name' => 'Remove Users', 'description' => 'Remove users from store'],
                    ['name' => 'Collect Cash from Users', 'description' => 'Collect cash from users'],
                    ['name' => 'View Invitations', 'description' => 'View user invitations'],
                    ['name' => 'Invite Users', 'description' => 'Send invitations to new users'],
                    ['name' => 'Resend Invitations', 'description' => 'Resend invitation emails'],
                    ['name' => 'Cancel Invitations', 'description' => 'Cancel pending invitations'],
                ],
                'Roles' => [
                    ['name' => 'View Roles', 'description' => 'View store roles'],
                    ['name' => 'Create Roles', 'description' => 'Create new roles'],
                    ['name' => 'Edit Roles', 'description' => 'Edit existing roles'],
                    ['name' => 'Delete Roles', 'description' => 'Delete roles'],
                ],
                'Settings' => [
                    ['name' => 'View Store Settings', 'description' => 'View store settings'],
                    ['name' => 'Edit Store Settings', 'description' => 'Edit store settings'],
                ],
                'Widgets' => [
                    ['name' => 'View Sales Dashboard Stats Widget', 'description' => 'View sales dashboard stats widget'],
                    ['name' => 'View Customer Stats Widget', 'description' => 'View customer stats widget'],
                    ['name' => 'View Supplier Stats Widget', 'description' => 'View supplier stats widget'],
                    ['name' => 'View Stock Levels Alerts Widget', 'description' => 'View stock level alerts widget'],
                    ['name' => 'View Daily Sales Chart Widget', 'description' => 'View daily sales chart widget'],
                    ['name' => 'View Monthly Sales Chart Widget', 'description' => 'View monthly sales chart widget'],
                    ['name' => 'View Yearly Sales Chart Widget', 'description' => 'View yearly sales chart widget'],
                    ['name' => 'View Latest Transactions Widget', 'description' => 'View latest transactions widget'],
                    ['name' => 'View Product Stats Widget', 'description' => 'View product stats widget'],
                    ['name' => 'View Customer Stats Overview Widget', 'description' => 'View customer stats overview widget'],
                    ['name' => 'View Customer Payment Stats Widget', 'description' => 'View customer payment stats widget'],
                    ['name' => 'View Supplier Stats Overview Widget', 'description' => 'View supplier stats overview widget'],
                    ['name' => 'View Supplier Payment Stats Widget', 'description' => 'View supplier payment stats widget'],
                    ['name' => 'View Sales Stats Widget', 'description' => 'View sales stats widget'],
                ],
            ],
            'admin' => [],
        ];
    }
}
